import java.io.*;

public class MyVersionObject implements Serializable {
  // The following SUID was generated by serialver utility like this:
  // > serialver -classpath . MyVersionObject
  static final long serialVersionUID  = -9205609326869736211L;
  private int i;
  private String s;

  //  Uncomment the next two lines to verify that default values will be substituted if
  //  the value is not present in the stream at deserialization time.
  //  private int i2 = -1; private String s2 = "This is the new String field";

  MyVersionObject() {
    i = 512;
    s = new String( "Instance of MyVersionObject..." );
  }

  public int getI() {
    return i;
  }

  public String getS() {
    return s;
  }
}
